name: 'Push Notifications via Bark'

description: >
  Push Notifications via Bark

inputs:
  key:
    description: 'Your secret key, it is required'
    required: true
  host:
    description: 'Your Bark host, the default is https://api.day.app'
    required: false
    default: 'https://api.day.app'
  title:
    description: 'Message title'
    required: false
  body:
    description: 'Message body'
    required: false
  sound:
    description: 'Message sound'
    required: false
    default: 'birdsong'
  isArchive:
    description: 'Whether to archive the message'
    required: false
  url:
    description: 'Message URL'
    required: false
  automaticallyCopy:
    description: 'Whether to automatically copy the message'
    required: false
  copy:
    description: 'Message to be copied'
    required: false
  icon:
    description: 'Message icon'
    required: false
  group:
    description: 'Message group'
    required: false
    default: 'github'
  
outputs:
  martix:
    description: 'The matrix of the job'
    value: ${{ steps.bark_push.outputs.matrix }}

runs:
  using: 'composite'
  steps:
    - name: Run notification script
      shell: bash
      run: $GITHUB_ACTION_PATH/script.sh
      env:
        INPUT_KEY: ${{ inputs.key }}
        INPUT_HOST: ${{ inputs.host }}
        INPUT_TITLE: ${{ inputs.title }}
        INPUT_BODY: ${{ inputs.body }}
        INPUT_SOUND: ${{ inputs.sound }}
        INPUT_IS_ARCHIVE: ${{ inputs.isArchive }}
        INPUT_URL: ${{ inputs.url }}
        INPUT_AUTOMATICALLY_COPY: ${{ inputs.automaticallyCopy }}
        INPUT_COPY: ${{ inputs.copy }}
        INPUT_GROUP: ${{ inputs.group }}
        INPUT_ICON: ${{ inputs.icon }}
        