ARG GO_VERSION_TARGET=1.20

FROM golang:${GO_VERSION_TARGET} as gosrc
#FROM jenkinsci/jnlp-slave
#FROM jenkins/agent:latest-bullseye-jdk17
FROM jenkins/inbound-agent:latest-jdk17
ARG GO_BASE_PATH=/usr/local/go

COPY --from=gosrc ${GO_BASE_PATH} ${GO_BASE_PATH}
COPY --from=gosrc /go ${HOME}

ENV GOPATH=${HOME}
ENV PATH="${GOPATH}/bin:${GO_BASE_PATH}/bin:${PATH}"
ENV CGO_ENABLED=0


#
# Install a bunch of web development related packages
# As well as sudo to allow to hack the image in jenkins
#
USER root

# Getting recent php versions
#COPY dotdeb.list /etc/apt/sources.list.d/dotdeb.list
#RUN wget -O- https://www.dotdeb.org/dotdeb.gpg | apt-key add -

# Get a recent version of MySQL
#RUN apt-key adv --keyserver pgp.mit.edu --recv-keys 5072E1F5
#COPY mysql.list /etc/apt/sources.list.d/mysql.list



# Avoid ERROR: invoke-rc.d: policy-rc.d denied execution of start.
RUN echo "#!/bin/sh\nexit 0" > /usr/sbin/policy-rc.d

# Got up-to-date shit :)

RUN sed -i 's/deb.debian.org/mirrors.ustc.edu.cn/g' /etc/apt/sources.list.d/debian.sources
RUN sed -i 's|security.debian.org/debian-security|mirrors.ustc.edu.cn/debian-security|g' /etc/apt/sources.list.d/debian.sources
#RUN apt-get update -y
#RUN apt-get dist-upgrade -y

# Getting recent node version
# RUN curl -sL https://deb.nodesource.com/setup_7.x | bash -
RUN curl -fsSL https://deb.nodesource.com/setup_18.x | bash - && apt-get install -y nodejs && node -v
# Configure Mysql
#RUN echo 'mysql-community-server mysql-community-server/root-pass password root' | debconf-set-selections
#RUN echo 'mysql-community-server mysql-community-server/re-root-pass password root' | debconf-set-selections

RUN apt-get install -qy \
    apt-transport-https \
    curl \
    build-essential \
    ruby ruby-dev \
    git wget
#    elasticsearch \
#    sudo


# All the bullshit
RUN apt-get install -qy \
     python3 \
     python3-requests \
     python3-pip
#     nano
#     golang 

#tools for devops
RUN apt-get install -qy ansible

#env KUBECTL_VERSION=1.22.2

#RUN curl -sLO https://storage.googleapis.com/kubernetes-release/release/v${KUBECTL_VERSION}/bin/linux/amd64/kubectl && \
#        mv kubectl /usr/bin/kubectl && \
#        chmod +x /usr/bin/kubectl

#COPY java.security  /usr/local/openjdk-8/jre/lib/security/

RUN wget http://gosspublic.alicdn.com/ossutil/1.7.6/ossutil64 && \
    mv ossutil64 /usr/bin/ && \
    chmod 755 /usr/bin/ossutil64

RUN npm install -g yarn
RUN npm install -g cnpm
RUN npm install -g n
RUN n 16.17
RUN npm install -g pnpm

# cleanup
RUN apt-get clean
RUN rm -f /wheels/*
RUN apt-get remove -y -q libxslt1-dev libxml2-dev libpq-dev libldap2-dev libsasl2-dev libssl-dev
RUN rm -rf /var/lib/apt/lists/*
RUN rm /tmp/req.txt