name: Flush cdn when push doc

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/push-doc.yml
      - docs/**

jobs:
  python_flush_cnd:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Flush CDN
        env:
          SECRET_ID: ${{ secrets.SecretId }}      # 传入鉴权信息
          SECRET_KEY: ${{ secrets.SecretKey }}
        run: |                                    # 安装 sdk 并运行刷新脚本
          pip install --upgrade tencentcloud-sdk-python && cd .github/workflows
          python flush-cdn.py -i $SECRET_ID -k $SECRET_KEY
  barks:
    runs-on: ubuntu-22.04
    steps:
      - name: Call Bark
        env:
          BARKURL: ${{ secrets.BARKURL }}      # 传入鉴权信息  :
          TITLE: 'Page 更新'
          BODY: '已推送。'
        run: |
          curl -X POST $BARKURL/$TITLE/$BODY?icon=https://pngimg.com/uploads/github/github_PNG22.png
